const characterTitle = {
  // ... 从旧文件第339行起复制
  //天罡星
  sh_songjiang: "<font color=#99FFFF>" + "天魁星.呼保义" + "</font>",
  sh_wuyong: "<font color=#99FFFF>" + "天机星.智多星" + "</font>",
  sh_gongsunsheng: "<font color=#99FFFF>" + "天闲星.入云龙" + "</font>",
  sh_guansheng: "<font color=#99FFFF>" + "天勇星.大刀" + "</font>",
  sh_qinming: "<font color=#99FFFF>" + "天猛星.霹雳火" + "</font>",
  sh_huyanzhuo: "<font color=#99FFFF>" + "天威星.双鞭" + "</font>",
  sh_huarong: "<font color=#99FFFF>" + "天英星.小李广" + "</font>",
  sh_chaijin: "<font color=#99FFFF>" + "天贵星.小旋风" + "</font>",
  sh_liying: "<font color=#99FFFF>" + "天富星.扑天雕" + "</font>",
  sh_zhutong: "<font color=#99FFFF>" + "天满星.美髯公" + "</font>",
  sh_luzhishen: "<font color=#99FFFF>" + "天孤星.花和尚" + "</font>",
  sh_dongping: "<font color=#99FFFF>" + "天立星.双枪将" + "</font>",
  sh_zhangqing: "<font color=#99FFFF>" + "天捷星.没羽箭" + "</font>",
  sh_yangzhi: "<font color=#99FFFF>" + "天暗星.青面兽" + "</font>",
  sh_xuning: "<font color=#99FFFF>" + "天佑星.金枪手" + "</font>",
  sh_suochao: "<font color=#99FFFF>" + "天空星.急先锋" + "</font>",
  sh_daizong: "<font color=#99FFFF>" + "天速星.神行太保" + "</font>",
  sh_liutang: "<font color=#99FFFF>" + "天异星.赤发鬼" + "</font>",
  sh_likui: "<font color=#99FFFF>" + "天杀星.黑旋风" + "</font>",
  sh_shijin: "<font color=#99FFFF>" + "天微星.九纹龙" + "</font>",
  sh_muhong: "<font color=#99FFFF>" + "天究星.没遮拦" + "</font>",
  sh_leiheng: "<font color=#99FFFF>" + "天退星.插翅虎" + "</font>",
  sh_lijun: "<font color=#99FFFF>" + "天寿星.混江龙" + "</font>",
  sh_ruanxiaoer: "<font color=#99FFFF>" + "天剑星.立地太岁" + "</font>",
  sh_zhangheng: "<font color=#99FFFF>" + "天平星.船火儿" + "</font>",
  sh_zhangshun: "<font color=#99FFFF>" + "天损星.浪里白条" + "</font>",

  sh_ruanxiaowu: "<font color=#99FFFF>" + "天罪星.短命二郎" + "</font>",
  sh_ruanxiaoqi: "<font color=#99FFFF>" + "天败星.活阎罗" + "</font>",
  sh_yangxiong: "<font color=#99FFFF>" + "天牢星.病关索" + "</font>",
  sh_shixiu: "<font color=#99FFFF>" + "天慧星.拼命三郎" + "</font>",
  sh_xiezhen: "<font color=#99FFFF>" + "天暴星.两头蛇" + "</font>",
  sh_xiebao: "<font color=#99FFFF>" + "天哭星.双尾蝎" + "</font>",
  sh_yanqing: "<font color=#99FFFF>" + "天巧星.浪子" + "</font>",

  //地煞星
  sh_zhuwu: "<font color=#FF7F00>" + "地魁星.神机军师" + "</font>",
  sh_huangxin: "<font color=#FF7F00>" + "地煞星.镇三山" + "</font>",
  sh_sunli: "<font color=#FF7F00>" + "地勇星.病尉迟" + "</font>",
  sh_xuanzan: "<font color=#FF7F00>" + "地杰星.丑郡马" + "</font>",
  sh_haosiwen: "<font color=#FF7F00>" + "地雄星.井木犴" + "</font>",
  sh_hantao: "<font color=#FF7F00>" + "地威星.百胜将" + "</font>",
  sh_pengqi: "<font color=#FF7F00>" + "地英星.天目将" + "</font>",
  sh_shantinggui: "<font color=#FF7F00>" + "地奇星.圣水将" + "</font>",
  sh_weidingguo: "<font color=#FF7F00>" + "地猛星.神火将" + "</font>",
  sh_xiaorang: "<font color=#FF7F00>" + "地文星.圣手书生" + "</font>",
  sh_peixuan: "<font color=#FF7F00>" + "地正星.铁面孔目" + "</font>",
  sh_oupeng: "<font color=#FF7F00>" + "地辟星.摩云金翅" + "</font>",
  sh_dengfei: "<font color=#FF7F00>" + "地阖星.火眼狻猊" + "</font>",
  sh_yanshun: "<font color=#FF7F00>" + "地强星.锦毛虎" + "</font>",
  sh_yanglin: "<font color=#FF7F00>" + "地暗星.锦豹子" + "</font>",
  sh_lingzhen: "<font color=#FF7F00>" + "地轴星.轰天雷" + "</font>",
  sh_jiangjing: "<font color=#FF7F00>" + "地会星.神算子" + "</font>",
  sh_lvfang: "<font color=#FF7F00>" + "地佐星.小温侯" + "</font>",
  sh_guosheng: "<font color=#FF7F00>" + "地佑星.赛仁贵" + "</font>",
  sh_andaoquan: "<font color=#FF7F00>" + "地灵星.神医" + "</font>",
  sh_huangfuduan: "<font color=#FF7F00>" + "地兽星.紫髯伯" + "</font>",
  sh_wangying: "<font color=#FF7F00>" + "地微星.矮脚虎" + "</font>",
  sh_husanniang: "<font color=#FF7F00>" + "地慧星.一丈青" + "</font>",
  sh_baoxu: "<font color=#FF7F00>" + "地暴星.丧门神" + "</font>",
  sh_fanrui: "<font color=#FF7F00>" + "地然星.混世魔王" + "</font>",
  sh_kongming: "<font color=#FF7F00>" + "地猖星.毛头星" + "</font>",
  sh_kongliang: "<font color=#FF7F00>" + "地狂星.独火星" + "</font>",
  sh_jindajian: "<font color=#FF7F00>" + "地巧星.玉臂匠" + "</font>",
  sh_malin: "<font color=#FF7F00>" + "地明星.铁笛仙" + "</font>",
  sh_tongwei: "<font color=#FF7F00>" + "地进星.出洞蛟" + "</font>",
  sh_tongmeng: "<font color=#FF7F00>" + "地退星.翻江蜃" + "</font>",
  sh_mengkang: "<font color=#FF7F00>" + "地满星.玉幡竿" + "</font>",
  sh_houjian: "<font color=#FF7F00>" + "地遂星.通臂猿" + "</font>",
  sh_zhengtianshou: "<font color=#FF7F00>" + "地异星.白面郎君" + "</font>",
  sh_taozongwang: "<font color=#FF7F00>" + "地理星.九尾龟" + "</font>",
  sh_songqing: "<font color=#FF7F00>" + "地俊星.铁扇子" + "</font>",
  sh_yuehe: "<font color=#FF7F00>" + "地乐星.铁叫子" + "</font>",
  sh_gongwang: "<font color=#FF7F00>" + "地捷星.花项虎" + "</font>",
  sh_dingdesun: "<font color=#FF7F00>" + "地速星.中箭虎" + "</font>",
  sh_muchun: "<font color=#FF7F00>" + "地镇星.小遮拦" + "</font>",
  sh_caozheng: "<font color=#FF7F00>" + "地稽星.操刀鬼" + "</font>",
  sh_xueyong: "<font color=#FF7F00>" + "地幽星.病大虫" + "</font>",
  sh_shien: "<font color=#FF7F00>" + "地伏星.金眼彪" + "</font>",
  sh_lizhong: "<font color=#FF7F00>" + "地僻星.打虎将" + "</font>",
  sh_zhoutong: "<font color=#FF7F00>" + "地空星.小霸王" + "</font>",
  sh_tanglong: "<font color=#FF7F00>" + "地孤星.金钱豹子" + "</font>",
  sh_zouyuan: "<font color=#FF7F00>" + "地短星.出林龙" + "</font>",
  sh_zourun: "<font color=#FF7F00>" + "地角星.独角龙" + "</font>",
  sh_zhugui: "<font color=#FF7F00>" + "地囚星.旱地忽律" + "</font>",
  sh_zhufu: "<font color=#FF7F00>" + "地藏星.笑面虎" + "</font>",
  sh_caifu: "<font color=#FF7F00>" + "地平星.铁臂膊" + "</font>",
  sh_caiqing: "<font color=#FF7F00>" + "地损星.一枝花" + "</font>",
  sh_lili: "<font color=#FF7F00>" + "地奴星.催命判官" + "</font>",
  sh_liyun: "<font color=#FF7F00>" + "地察星.青眼虎" + "</font>",
  sh_jiaoting: "<font color=#FF7F00>" + "地恶星.没面目" + "</font>",
  sh_shiyong: "<font color=#FF7F00>" + "地丑星.石将军" + "</font>",
  sh_sunxin: "<font color=#FF7F00>" + "地数星.小尉迟" + "</font>",
  sh_gudasao: "<font color=#FF7F00>" + "地阴星.母大虫" + "</font>",
  sh_zhangqing2: "<font color=#FF7F00>" + "地刑星.菜园子" + "</font>",
  sh_sunerniang: "<font color=#FF7F00>" + "地壮星.母夜叉" + "</font>",
  sh_wangdingliu: "<font color=#FF7F00>" + "地劣星.活闪婆" + "</font>",
  sh_yubaosi: "<font color=#FF7F00>" + "地健星.险道神" + "</font>",
  sh_baisheng: "<font color=#FF7F00>" + "地耗星.白日鼠" + "</font>",
  sh_shiqian: "<font color=#FF7F00>" + "地贼星.鼓上蚤" + "</font>",
  sh_duanjingzhu: "<font color=#FF7F00>" + "地狗星.金毛犬" + "</font>",

  //其他
  sh_wanglun: "<font color=#FFD700>" + "白衣秀士" + "</font>",
  sh_chaogai: "<font color=#FFD700>" + "千佛星.托塔天王" + "</font>",
  sh_ximenqing: "<font color=#FFD700>" + "大官人" + "</font>",
  sh_zhuzhuzhu: "<font color=#FFD700>" + "祝氏三杰" + "</font>",
  sh_zengzengzengzengzeng: "<font color=#FFD700>" + "曾家五虎" + "</font>",
  sh_caijing: "<font color=#8B008B>" + "太师" + "</font>",
  sh_tongguan: "<font color=#8B008B>" + "媪相" + "</font>",
  sh_gaoqiu: "<font color=#8B008B>" + "高太尉" + "</font>",
  sh_yangjian: "<font color=#8B008B>" + "杨太尉" + "</font>",
  sh_zhaoji: "<font color=#8B008B>" + "宋徽宗" + "</font>",
  sh_hongxin: "<font color=#FFD700>" + "洪太尉" + "</font>",
  //楚
  sh_lizhu: "<font color=#FF6200>" + "金剑先生" + "</font>",
  sh_duansanniang: "<font color=#FF6200>" + "淮西天魔" + "</font>",
  sh_koumie: "<font color=#FF6200>" + "毒焰鬼王" + "</font>",
  //辽
  sh_wuyanguang: "<font color=#00FFFF>" + "辽国第一上将" + "</font>",
  sh_yelvhui: "<font color=#00FFFF>" + "辽国狼主" + "</font>",
  sh_dalibo: "<font color=#00FFFF>" + "天寿公主" + "</font>",
  //南
  sh_baodaoyi: "<font color=#B22222>" + "灵应天师" + "</font>",
  sh_shibao: "<font color=#B22222>" + "南离大将军" + "</font>",
  sh_pangwanchun: "<font color=#B22222>" + "小养由基" + "</font>",
  //晋
  sh_qiaodaoqing: "<font color=#5C4033>" + "幻魔君" + "</font>",
  sh_tianhu: "<font color=#5C4033>" + "晋王" + "</font>",
  sh_qiuqiongying: "<font color=#5C4033>" + "琼矢镞" + "</font>",
};
export default characterTitle;
